version: '3.8'

services:

  postgresql:
    image: postgres:17.2
    container_name: postgresql
    restart: "no"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    networks:
      - backend
    ports:
      - 5433:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: "no"
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      ADMINER_DESIGN: brade
    networks:
      - backend
    ports:
      - 10000:8080

networks:
  backend:
    driver: bridge